import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Activity, Plus, X, Search, AlertCircle, CheckCircle, Info, ShieldAlert, Stethoscope } from 'lucide-react';
import { generateTextWithGemini } from '../api/gemini';
import { generateTextWithCohere } from '../api/cohere';
import { generateTextWithGroq } from '../api/groq';
import { generateTextFallback } from '../api/cascadeRouter';

export default function SymptomChecker() {
  const [symptoms, setSymptoms] = useState([]);
  const [input, setInput] = useState('');
  const [age, setAge] = useState('');
  const [gender, setGender] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const addSymptom = () => {
    if (input.trim() && !symptoms.includes(input.trim())) {
      setSymptoms([...symptoms, input.trim()]);
      setInput('');
    }
  };

  const removeSymptom = (s) => setSymptoms(symptoms.filter((x) => x !== s));

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') addSymptom();
  };

  const analyze = async () => {
    if (symptoms.length === 0) return;
    setIsAnalyzing(true);
    setError(null);
    setResult(null);

    try {
      const formatterPrompt = `You are an expert medical diagnostic AI.
Patient Profile: ${age ? age + '-year-old ' : ''}${gender || 'person'}.
Symptoms Reported: [${symptoms.join(', ')}].

CRITICAL INSTRUCTION: 
1. Evaluate the symptoms carefully and identify the most likely medical condition.
2. Ensure the condition is biologically possible for a ${age ? age + '-year-old ' : ''}${gender || 'person'}.
3. Provide a detailed, accurate medical analysis.

Generate your response in EXACTLY this JSON format (no markdown, no extra text):
{
  "possible_conditions": [
    {
      "name": "Primary Suspected Condition",
      "probability": "High",
      "description": "Provide a detailed medical description of the condition.",
      "symptoms_match": ["matched symptom 1", "matched symptom 2"]
    }
  ],
  "severity": "Mild", 
  "recommendation": "Specific medical advice for this condition.",
  "immediate_action": false,
  "precautions": ["List 3-4 specific precautions"],
  "specialist_recommendation": "Which specific specialist should they see?",
  "do_list": ["3 specific things to do"],
  "dont_list": ["3 specific things to avoid"],
  "questions_to_ask_doctor": ["3 relevant questions"],
  "disclaimer": "This analysis is generated by an AI assistant for educational purposes and is not a substitute for professional medical advice."
}`;

      const response = await generateTextFallback([
        { name: 'Gemini', fn: generateTextWithGemini, apiKey: import.meta.env.VITE_GEMINI_API_KEY_1 },
        { name: 'Cohere', fn: generateTextWithCohere, apiKey: import.meta.env.VITE_COHERE_API_KEY_1 },
        { name: 'Groq', fn: generateTextWithGroq, apiKey: import.meta.env.VITE_GROQ_API_KEY_1 }
      ], formatterPrompt);
      
      const cleaned = response.replace(/```json|```/g, '').trim();
      const finalResult = JSON.parse(cleaned);
      
      setResult(finalResult);
    } catch (err) {
      console.error("Symptom Analysis Flow Error:", err);
      setError("The AI Diagnostic Engine is currently unavailable. Please try again later.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const probabilityColor = (prob) => {
    switch (prob) {
      case 'High': return 'bg-red-50 text-red-700 border-red-200';
      case 'Medium': return 'bg-orange-50 text-orange-700 border-orange-200';
      default: return 'bg-blue-50 text-blue-700 border-blue-200';
    }
  };

  const severityColor = (sev) => {
    switch (sev) {
      case 'Severe': return 'bg-red-50 border-red-200 text-red-800';
      case 'Moderate': return 'bg-orange-50 border-orange-200 text-orange-800';
      default: return 'bg-green-50 border-green-200 text-green-800';
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-6 py-8 space-y-6">
      {/* Header */}
      <div className="text-center max-w-2xl mx-auto py-4">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-teal-50 text-teal-700 text-sm font-medium mb-4">
          <Activity className="w-4 h-4" />
          AI Symptom Analysis
        </div>
        <h2 className="text-3xl font-bold text-gray-900 mb-3">
          Check Your <span className="text-teal-600">Symptoms</span>
        </h2>
        <p className="text-gray-600">Enter your symptoms and get AI-powered insights about possible conditions</p>
        
        <div className="mt-4 flex justify-center">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-medium border border-blue-200">
            <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
            AI Diagnostic Engine Online
          </span>
        </div>
      </div>

      {/* Input Card */}
      <div className="p-6 rounded-2xl bg-white border border-gray-100 shadow-sm space-y-4">
        {/* Age & Gender */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Age</label>
            <input
              type="number"
              value={age}
              onChange={(e) => setAge(e.target.value)}
              placeholder="Enter your age"
              className="w-full px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:border-teal-400 text-sm"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Gender</label>
            <select
              value={gender}
              onChange={(e) => setGender(e.target.value)}
              className="w-full px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:border-teal-400 text-sm"
            >
              <option value="">Select gender</option>
              <option value="male">Male</option>
              <option value="female">Female</option>
              <option value="other">Other</option>
            </select>
          </div>
        </div>

        {/* Symptom Input */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Add Symptoms</label>
          <div className="flex gap-2">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="e.g. headache, fever, cough..."
              className="flex-1 px-4 py-2 rounded-xl border border-gray-200 focus:outline-none focus:border-teal-400 text-sm"
            />
            <button
              onClick={addSymptom}
              className="px-4 py-2 rounded-xl bg-teal-500 text-white hover:bg-teal-600 transition-colors flex items-center gap-1"
            >
              <Plus className="w-4 h-4" /> Add
            </button>
          </div>
        </div>

        {/* Symptoms Tags */}
        {symptoms.length > 0 && (
          <div className="flex flex-wrap gap-2">
            {symptoms.map((s) => (
              <span key={s} className="flex items-center gap-1 px-3 py-1 rounded-full bg-teal-50 text-teal-700 text-sm border border-teal-200">
                {s}
                <button onClick={() => removeSymptom(s)}>
                  <X className="w-3 h-3 hover:text-red-500" />
                </button>
              </span>
            ))}
          </div>
        )}

        {/* Analyze Button */}
        <button
          onClick={analyze}
          disabled={symptoms.length === 0 || isAnalyzing}
          className="w-full py-3 rounded-xl bg-gradient-to-r from-teal-500 to-cyan-500 text-white font-medium hover:from-teal-600 hover:to-cyan-600 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
        >
          {isAnalyzing ? (
            <>
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              Analyzing...
            </>
          ) : (
            <>
              <Search className="w-4 h-4" />
              Analyze Symptoms
            </>
          )}
        </button>
      </div>

      {error && (
        <div className="p-4 rounded-xl bg-red-50 border border-red-200 text-red-700 flex items-center gap-2">
          <AlertCircle className="w-5 h-5" /> {error}
        </div>
      )}

      {/* Results */}
      <AnimatePresence>
        {result && (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
            {/* Severity */}
            <div className={`p-4 rounded-2xl border ${severityColor(result.severity)}`}>
              <div className="flex items-center gap-2 font-semibold">
                <AlertCircle className="w-5 h-5" />
                Severity: {result.severity}
                {result.immediate_action && (
                  <span className="ml-auto text-sm px-3 py-1 rounded-full bg-red-100 text-red-700 border border-red-200">
                    ⚠️ Seek immediate care
                  </span>
                )}
              </div>
              <p className="mt-2 text-sm">{result.recommendation}</p>
            </div>

            {/* Possible Conditions */}
            {result.possible_conditions?.length > 0 && (
              <div className="p-6 rounded-2xl bg-white border border-gray-100 shadow-sm">
                <h3 className="font-semibold text-gray-900 mb-4 text-lg">Predicted Conditions</h3>
                <div className="space-y-3">
                  {result.possible_conditions.map((c, i) => (
                    <div key={i} className="p-4 rounded-xl bg-teal-50 border border-teal-100">
                      <div className="flex items-center justify-between mb-2">
                        <p className="font-medium text-teal-900">{c.name}</p>
                        <span className={`text-xs px-2 py-1 rounded-full border font-medium ${probabilityColor(c.probability)}`}>
                          {c.probability}
                        </span>
                      </div>
                      <p className="text-sm text-teal-800">{c.description}</p>
                      {c.symptoms_match?.length > 0 && (
                        <div className="flex flex-wrap gap-1 mt-2">
                          {c.symptoms_match.map((s, j) => (
                            <span key={j} className="text-xs px-2 py-0.5 rounded-full bg-white text-teal-700 border border-teal-200">{s}</span>
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Precautions & Specialist */}
            <div className="grid md:grid-cols-2 gap-4">
              {result.precautions?.length > 0 && (
                <div className="p-6 rounded-2xl bg-blue-50 border border-blue-100">
                  <h3 className="font-semibold text-blue-900 mb-3 flex items-center gap-2">
                    <ShieldAlert className="w-5 h-5 text-blue-600" /> Precautions
                  </h3>
                  <ul className="space-y-2">
                    {result.precautions.map((d, i) => (
                      <li key={i} className="text-sm text-blue-800 flex items-start gap-2">
                        <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-500 flex-shrink-0" />{d}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              {result.specialist_recommendation && (
                <div className="p-6 rounded-2xl bg-purple-50 border border-purple-100">
                  <h3 className="font-semibold text-purple-900 mb-3 flex items-center gap-2">
                    <Stethoscope className="w-5 h-5 text-purple-600" /> Specialist Recommendation
                  </h3>
                  <p className="text-sm text-purple-800">{result.specialist_recommendation}</p>
                </div>
              )}
            </div>

            {/* Do's and Don'ts */}
            <div className="grid md:grid-cols-2 gap-4">
              {result.do_list?.length > 0 && (
                <div className="p-6 rounded-2xl bg-green-50 border border-green-100">
                  <h3 className="font-semibold text-green-900 mb-3 flex items-center gap-2">
                    <CheckCircle className="w-5 h-5" /> What To Do
                  </h3>
                  <ul className="space-y-2">
                    {result.do_list.map((d, i) => (
                      <li key={i} className="text-sm text-green-800 flex items-start gap-2">
                        <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-green-500 flex-shrink-0" />{d}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              {result.dont_list?.length > 0 && (
                <div className="p-6 rounded-2xl bg-red-50 border border-red-100">
                  <h3 className="font-semibold text-red-900 mb-3 flex items-center gap-2">
                    <X className="w-5 h-5" /> What To Avoid
                  </h3>
                  <ul className="space-y-2">
                    {result.dont_list.map((d, i) => (
                      <li key={i} className="text-sm text-red-800 flex items-start gap-2">
                        <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-red-500 flex-shrink-0" />{d}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* Questions for Doctor */}
            {result.questions_to_ask_doctor?.length > 0 && (
              <div className="p-6 rounded-2xl bg-white border border-gray-100 shadow-sm">
                <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <Info className="w-5 h-5 text-teal-500" /> Questions to Ask Your Doctor
                </h3>
                <ul className="space-y-2">
                  {result.questions_to_ask_doctor.map((q, i) => (
                    <li key={i} className="text-sm text-gray-700 flex items-start gap-2">
                      <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-teal-500 flex-shrink-0" />{q}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Disclaimer */}
            <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-sm text-amber-800">
              ⚠️ {result.disclaimer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}